### ISSUE TITLE
Abuse

### ISSUE THREAD

**Issue by adreewwm** [gbutler69/rumbrello#1]
Gerald E Butler, I am reporting you to several consumer protection sites for workplace abuse. I will post detailed reports on those sites, using your name and previous known address such as 2807 Summit Rd, Akron, OH. As President and Owner of Butler Software LLC, you have sexually harassed me and several other workers. From inappropriate touching to lewd solicitation. I will contact your previous employers at Clinical Specialities Inc, Onshore Momentum, National City Corp and several others, to warn them that to act as a positive referral on your behalf is to support someone who has used his position as an employer to abuse his workers.

Kent State university will also hear from me. I will notify - via mail - relatives such Maribel Butler and Nicole A Butler of your actions, as well. Also via 3309839698 and 3303100125. I have hired a professional to uncover your social media accounts on Twitter and other forums. You will be exposed there as well.

**Comment by gbutler69** [comment]
Whoever you are, I look forward to seeing you in court. I will sue you for libel and see that you are jailed for fraud. I've reported you to the GitHUB management. Fuck Off you worthless piece of shit!
